/**
 * Exports the ABIs and deployment records the web app needs, so the dashboard
 * never carries a hand-copied ABI that can drift from what is deployed.
 *
 *   npx hardhat run scripts/export-abis.ts
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";

const artifact = (name: string, file = name) =>
  JSON.parse(readFileSync(`artifacts/contracts/${file}.sol/${name}.json`, "utf8")).abi;

const abis = {
  LetterOfCredit: artifact("LetterOfCredit"),
  IdentityRegistry: artifact("IdentityRegistry", "erc8004/IdentityRegistry"),
  ReputationRegistry: artifact("ReputationRegistry", "erc8004/ReputationRegistry"),
  ValidationRegistry: artifact("ValidationRegistry", "erc8004/ValidationRegistry"),
  ServiceVendor: artifact("ServiceVendor", "demo/ServiceVendor"),
};

mkdirSync("web/lib/generated", { recursive: true });
writeFileSync(
  "web/lib/generated/abis.ts",
  `// Generated by scripts/export-abis.ts — do not edit.\n` +
    `export const abis = ${JSON.stringify(abis, null, 2)} as const;\n`,
);

// Ship whichever networks have been deployed, so the app can offer a chain switch.
const deployments: Record<string, unknown> = {};
if (existsSync("deployments")) {
  for (const f of readdirSync("deployments")) {
    const m = /^(\d+)\.json$/.exec(f);
    if (m && m[1] !== "31337") {
      deployments[m[1]] = JSON.parse(readFileSync(`deployments/${f}`, "utf8"));
    }
  }
}
writeFileSync(
  "web/lib/generated/deployments.ts",
  `// Generated by scripts/export-abis.ts — do not edit.\n` +
    `export const deployments = ${JSON.stringify(deployments, null, 2)} as const;\n`,
);

/**
 * Copy the documentation into the app.
 *
 * Vercel builds this project with `web` as its root directory, so anything
 * outside web/ simply does not exist at build time. The docs are copied in here
 * rather than read across the directory boundary, which keeps /docs working on a
 * deployment without a monorepo build config.
 */
const DOCS: { slug: string; title: string; blurb: string; source: string }[] = [
  {
    slug: "overview",
    title: "Overview",
    blurb: "What AVAL is, why a documentary credit, and how the pieces fit together.",
    source: "README.md",
  },
  {
    slug: "research",
    title: "BOT Chain research",
    blurb: "Verified chain facts, three corrections to widely-repeated claims, and the ERC-8004 gap.",
    source: "docs/RESEARCH.md",
  },
  {
    slug: "submission",
    title: "Submission pack",
    blurb: "The pitch, the demo script, the mainnet runbook, and the limits stated up front.",
    source: "docs/SUBMISSION.md",
  },
];

mkdirSync("web/content", { recursive: true });
const index: { slug: string; title: string; blurb: string }[] = [];
for (const doc of DOCS) {
  if (!existsSync(doc.source)) {
    console.log(`  skipped ${doc.source} (not found)`);
    continue;
  }
  writeFileSync(`web/content/${doc.slug}.md`, readFileSync(doc.source, "utf8"));
  index.push({ slug: doc.slug, title: doc.title, blurb: doc.blurb });
}
writeFileSync(
  "web/lib/generated/docs.ts",
  `// Generated by scripts/export-abis.ts — do not edit.\n` +
    `export const docsIndex = ${JSON.stringify(index, null, 2)} as const;\n`,
);

console.log(`exported ${Object.keys(abis).length} ABIs`);
console.log(`exported deployments for chains: ${Object.keys(deployments).join(", ") || "(none)"}`);
console.log(`exported ${index.length} documents to web/content/`);
