// Exports ABIs, deployments and docs for the web app: npx hardhat run scripts/export-abis.ts
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";

const artifact = (name: string, file = name) =>
  JSON.parse(readFileSync(`artifacts/contracts/${file}.sol/${name}.json`, "utf8")).abi;

const abis = {
  LetterOfCredit: artifact("LetterOfCredit"),
  IdentityRegistry: artifact("IdentityRegistry", "erc8004/IdentityRegistry"),
  ReputationRegistry: artifact("ReputationRegistry", "erc8004/ReputationRegistry"),
  ValidationRegistry: artifact("ValidationRegistry", "erc8004/ValidationRegistry"),
  ServiceVendor: artifact("ServiceVendor", "demo/ServiceVendor"),
};

mkdirSync("web/lib/generated", { recursive: true });
writeFileSync(
  "web/lib/generated/abis.ts",
  `// Generated by scripts/export-abis.ts, do not edit.\n` +
    `export const abis = ${JSON.stringify(abis, null, 2)} as const;\n`,
);

// Ship whichever networks have been deployed, so the app can offer a chain switch.
const deployments: Record<string, unknown> = {};
if (existsSync("deployments")) {
  for (const f of readdirSync("deployments")) {
    const m = /^(\d+)\.json$/.exec(f);
    if (m && m[1] !== "31337") {
      deployments[m[1]] = JSON.parse(readFileSync(`deployments/${f}`, "utf8"));
    }
  }
}
writeFileSync(
  "web/lib/generated/deployments.ts",
  `// Generated by scripts/export-abis.ts, do not edit.\n` +
    `export const deployments = ${JSON.stringify(deployments, null, 2)} as const;\n`,
);

// Docs are copied into web/ because Vercel builds with web/ as its root directory.
const DOCS: { slug: string; title: string; blurb: string; source: string }[] = [
  {
    slug: "overview",
    title: "Overview",
    blurb: "What AVAL is, where it runs, and how to try it in one minute.",
    source: "README.md",
  },
  {
    slug: "how-it-works",
    title: "How it works",
    blurb: "The lifecycle, the four parties, and Mr. A's supplier payments as a worked example.",
    source: "docs/HOW-IT-WORKS.md",
  },
  {
    slug: "guide",
    title: "Using the dapp",
    blurb: "Every page and every function, plus a five-minute test drive that needs no wallet.",
    source: "docs/GUIDE.md",
  },
  {
    slug: "research",
    title: "BOT Chain research",
    blurb: "Verified chain facts, three corrections to widely-repeated claims, and the ERC-8004 gap.",
    source: "docs/RESEARCH.md",
  },
];

mkdirSync("web/content", { recursive: true });
const index: { slug: string; title: string; blurb: string }[] = [];
for (const doc of DOCS) {
  if (!existsSync(doc.source)) {
    console.log(`  skipped ${doc.source} (not found)`);
    continue;
  }
  writeFileSync(`web/content/${doc.slug}.md`, readFileSync(doc.source, "utf8"));
  index.push({ slug: doc.slug, title: doc.title, blurb: doc.blurb });
}
writeFileSync(
  "web/lib/generated/docs.ts",
  `// Generated by scripts/export-abis.ts, do not edit.\n` +
    `export const docsIndex = ${JSON.stringify(index, null, 2)} as const;\n`,
);

console.log(`exported ${Object.keys(abis).length} ABIs`);
console.log(`exported deployments for chains: ${Object.keys(deployments).join(", ") || "(none)"}`);
console.log(`exported ${index.length} documents to web/content/`);
