/**
 * Exports the ABIs and deployment records the web app needs, so the dashboard
 * never carries a hand-copied ABI that can drift from what is deployed.
 *
 *   npx hardhat run scripts/export-abis.ts
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";

const artifact = (name: string, file = name) =>
  JSON.parse(readFileSync(`artifacts/contracts/${file}.sol/${name}.json`, "utf8")).abi;

const abis = {
  LetterOfCredit: artifact("LetterOfCredit"),
  IdentityRegistry: artifact("IdentityRegistry", "erc8004/IdentityRegistry"),
  ReputationRegistry: artifact("ReputationRegistry", "erc8004/ReputationRegistry"),
  ValidationRegistry: artifact("ValidationRegistry", "erc8004/ValidationRegistry"),
  ServiceVendor: artifact("ServiceVendor", "demo/ServiceVendor"),
};

mkdirSync("web/lib/generated", { recursive: true });
writeFileSync(
  "web/lib/generated/abis.ts",
  `// Generated by scripts/export-abis.ts — do not edit.\n` +
    `export const abis = ${JSON.stringify(abis, null, 2)} as const;\n`,
);

// Ship whichever networks have been deployed, so the app can offer a chain switch.
const deployments: Record<string, unknown> = {};
if (existsSync("deployments")) {
  for (const f of readdirSync("deployments")) {
    const m = /^(\d+)\.json$/.exec(f);
    if (m && m[1] !== "31337") {
      deployments[m[1]] = JSON.parse(readFileSync(`deployments/${f}`, "utf8"));
    }
  }
}
writeFileSync(
  "web/lib/generated/deployments.ts",
  `// Generated by scripts/export-abis.ts — do not edit.\n` +
    `export const deployments = ${JSON.stringify(deployments, null, 2)} as const;\n`,
);

console.log(`exported ${Object.keys(abis).length} ABIs`);
console.log(`exported deployments for chains: ${Object.keys(deployments).join(", ") || "(none)"}`);
